SEAT_STATE_EMPTY = "Empty"
SEAT_STATE_RESERVED = "Reserved"
SEAT_STATE_BOOKED = "Booked"
DISPLAY_EMPTY = "."
DISPLAY_RESERVED = "o"
DISPLAY_BOOKED = "#"
BOOKING_STATUS_RESERVED = "Reserved"
BOOKING_STATUS_CONFIRMED = "Confirmed"
BOOKING_ID_PREFIX = "GIC"
ALPHABET_LIST = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
PROCESSING_BOOKING_MODE = "Booking_Mode"
PROCESSING_CHECKING_MODE = "Checking_Mode"
MAX_ROWS = 26
MAX_COLUMNS = 50
